version: '3'

services:
  nginx:
    image: nginx:latest
    container_name: webserver
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - /home/trojan-go/nginxhtml:/usr/share/nginx/html
  acme:
    image: neilpang/acme.sh:latest
    container_name: acme
    volumes:
      - /home/trojan-go/config:/acme.sh
      - /home/trojan-go/nginxhtml:/usr/share/nginx/html
    network_mode: "host"
    command: >
      sh -c "acme.sh --register-account  -m mysesrver@example.com --server zerossl &&
             acme.sh --issue  -d mytr.antvi.net -w /usr/share/nginx/html"
    depends_on:
      - nginx
  trojan-go:
    image: teddysun/trojan-go:latest
    container_name: trojan-go
    restart: unless-stopped
    network_mode: "host"
    volumes:
      - /home/trojan-go/config:/etc/trojan-go
    depends_on:
      - nginx
      - acme
